on: release
name: Build Release
jobs:
  build:
    name: Build Distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.6'
      - run: >
          make